// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Guard: if env vars are empty (deploying as static vitrine), expose a
// SILENT chainable proxy that mimics Supabase's API shape so the React tree
// can still mount and run. Any actual DB/auth operation is a no-op:
//  - method calls return Promise.resolve({ data: null, error: null }) by default
//  - property access returns another silent proxy
//  - subscription methods return { data: { subscription: { unsubscribe(){} } } }
const hasCreds = !!SUPABASE_URL && !!SUPABASE_PUBLISHABLE_KEY;

const silentNoop = (): any => {
  const promise = Promise.resolve({ data: null, error: null });
  const subscription = { unsubscribe() {}, on() { return subscription; } };
  const handler: ProxyHandler<any> = {
    get(_t, prop) {
      // Make it thenable / await-friendly
      if (prop === "then" || prop === "catch" || prop === "finally") {
        return (promise as any)[prop].bind(promise);
      }
      // Subscription shape (onAuthStateChange returns { data: { subscription } })
      if (prop === "data") {
        return { subscription, user: null, session: null };
      }
      if (prop === "error") return null;
      if (prop === "subscription") return subscription;
      if (prop === "unsubscribe") return () => {};
      // Anything else → chainable callable proxy
      return silentNoop();
    },
    apply() {
      return silentNoop();
    },
    has() { return true; },
  };
  return new Proxy(function () {}, handler);
};

export const supabase = hasCreds
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : (silentNoop() as ReturnType<typeof createClient<Database>>);
