-- ═════════════════════════════════════════════════════════
-- Klary — Seed Hypothèque v2 : +25 questions techniques
--   • Frais annexes, cédules, régimes fiscaux
--   • Types de biens (principal / secondaire / locatif)
--   • Financement construction, blend & extend, forward
--   • Régime matrimonial et succession
--   • Assurance liée au bien
-- ═════════════════════════════════════════════════════════

INSERT INTO training_questions
  (module_key, external_id, category, question_type, question, options, correct, explanation, why_wrong, consequence, active) VALUES

('hypotheque','H011','Hypothèque — LTV','single',
$QK$Que signifie le ratio LTV (Loan-to-Value) et quels sont les seuils FINMA pour résidence principale ?$QK$,
$QK$["LTV = valeur du prêt / valeur du bien. Peut aller jusqu'à 100%", "LTV = valeur du prêt / valeur du bien. Résidence principale : max 80% (dont 65% en 1er rang stable + 15% en 2e rang à amortir sur 15 ans). Résidence SECONDAIRE : max 70% (règles plus strictes). LOCATIF : encore plus strict.", "LTV max = 50%", "Peu importe le LTV"]$QK$::jsonb,
1,
$QK$LTV = Loan-to-Value ratio, indicateur de risque bancaire. FINMA/ASB fixe : (1) Résidence principale = 80% max, découpé 65% (1er rang, sans amortissement) + 15% (2e rang, amortissement sur 15 ans max). (2) Résidence secondaire = 70% max. (3) Locatif = 75% max avec conditions renforcées. Au-delà, refus banque quasi-systématique.$QK$,
$QK$["Faux — seuils réglementaires stricts.", null, "Sous-estime — LTV va jusqu'à 80% en principale.", "Faux — le LTV détermine la faisabilité."]$QK$::jsonb,
$QK$Erreur = calcul du besoin de financement client sans respect LTV → refus banque tardif → drame immo. Le courtier doit vérifier LTV dès la 1re simulation.$QK$,
TRUE),

('hypotheque','H012','Hypothèque — Résidence secondaire','single',
$QK$Un client veut acheter un chalet aux Diablerets comme résidence secondaire. Différences avec une résidence principale ?$QK$,
$QK$["Aucune", "Apport minimum PLUS ÉLEVÉ (30% souvent au lieu de 20%), taux hypothécaire majoré (+20-40 bps), amortissement obligatoire souvent renforcé, restrictions LEX WEBER (interdiction dans communes >20% résidences secondaires — actuel 60% du territoire), LPP EPL INTERDIT pour résidence secondaire.", "Taux moins cher", "Aucune restriction"]$QK$::jsonb,
1,
$QK$Résidence secondaire : régime beaucoup plus strict. Points critiques : (1) apport 30% minimum, (2) LPP EPL EXCLU (art. 30c LPP réserve la résidence PRINCIPALE), (3) LEX WEBER limite à 20% de résidences secondaires par commune → dans les communes touristiques, il faut trouver un bien déjà existant, (4) taux hypothécaire 20-40 bps de plus, (5) fiscalité valeur locative également applicable.$QK$,
$QK$["Faux — nombreuses différences.", null, "Faux — c'est plus cher, pas moins.", "Faux — LEX WEBER et 30% apport."]$QK$::jsonb,
$QK$Erreur = client qui prépare son financement en pensant utiliser sa LPP EPL pour un chalet → refus banque catastrophique. Le courtier doit clarifier IMMÉDIATEMENT le type de bien (principal vs secondaire).$QK$,
TRUE),

('hypotheque','H013','Hypothèque — Bien locatif','single',
$QK$Un client veut acheter un immeuble locatif de 4 appartements. Financement possible chez une banque suisse ?$QK$,
$QK$["Aucun financement", "Oui — LTV max 75% avec critères renforcés : apport 25%+ obligatoire en fonds durs, capacité financière basée sur les LOYERS ATTENDUS − une décote de vacance (5-10%) + charges d'entretien (10-15% des loyers), amortissement obligatoire similaire au 2e rang résidence principale. Analyse cash-flow location clé.", "Financement identique à résidence principale", "Uniquement pour SA (sociétés)"]$QK$::jsonb,
1,
$QK$Financement bien locatif = régime spécifique. La banque calcule la faisabilité sur les LOYERS attendus (après décote de vacance et d'entretien) plutôt que sur le revenu du client. Amortissement obligatoire sur le 2e rang. Apport 25%+ en fonds durs. Fiscalement : les loyers sont imposés + intérêts hypothécaires déductibles + entretien déductible → optimisation possible.$QK$,
$QK$["Faux — financement locatif standard.", null, "Faux — règles très différentes.", "Faux — accessible personne physique."]$QK$::jsonb,
$QK$Erreur = ne pas maîtriser le calcul cash-flow locatif → client s'engage dans un projet peu rentable → défaut de paiement quelques années plus tard.$QK$,
TRUE),

('hypotheque','H014','Hypothèque — Frais annexes','single',
$QK$Achat d'un bien 1,2 M CHF : quels FRAIS ANNEXES (hors apport) le client doit-il prévoir en plus de son apport ?$QK$,
$QK$["Aucun", "1-5 % du prix selon canton : notaire (0,5-1%), registre foncier (0,25-0,5%), droits de mutation (variable canton : 0-3,3% — nul à Zurich, 3,3% à Genève, 2,2% à Vaud, etc.), commission courtier immobilier si applicable (2-3% payée par vendeur usuellement).", "10 % du prix minimum", "5 000 CHF fixes"]$QK$::jsonb,
1,
$QK$Frais annexes majeurs à budgéter. Variables selon canton : Vaud = 3-4% (notaire + registre + droits de mutation 2,2%). Genève = 4-6% (droits mutation 3%). Zurich = 1,5-2% (pas de droit de mutation). Le budget doit inclure ces frais en PLUS de l'apport 20%. Sur 1,2M CHF Vaud = 36-48k CHF de frais annexes → 20% apport (240k) + frais (48k) = 288k à disposition minimum.$QK$,
$QK$["Faux — frais notables.", null, "Sur-estime pour la plupart des cantons.", "Faux — variables selon canton et montant."]$QK$::jsonb,
$QK$Erreur = simulation faisabilité qui oublie les frais annexes → client se retrouve court de 30-50k CHF à la signature → recherche d'urgence de financement supplémentaire. Défaut de conseil.$QK$,
TRUE),

('hypotheque','H015','Hypothèque — Cédule','single',
$QK$Différence entre cédule hypothécaire de REGISTRE et cédule hypothécaire au PORTEUR ?$QK$,
$QK$["Aucune", "REGISTRE : inscrite au registre foncier au nom du créancier, transfert nécessite modification registre — sécurité renforcée. AU PORTEUR : titre physique circulant comme un billet à ordre, transférable par simple remise — plus flexible mais risque en cas de vol/perte. Depuis 2012, seule la cédule DE REGISTRE peut être émise nouvellement.", "Cédule au porteur illégale", "Aucune conséquence pratique"]$QK$::jsonb,
1,
$QK$Réforme 2012 : plus d'émission de nouvelles cédules au porteur (art. 842 CC). Toutes les nouvelles cédules sont "de registre" (inscription obligatoire au registre foncier). Les cédules au porteur existantes restent valides mais sont progressivement converties. Point CRITIQUE en cas d'ancien financement : vérifier l'état de la cédule et prévoir la conversion si nécessaire.$QK$,
$QK$["Faux — 2 types distincts avec conséquences pratiques.", null, "Faux — les cédules au porteur existantes restent valides.", "Faux — conséquences sur transferts et sécurité."]$QK$::jsonb,
$QK$Erreur = ignorer le type de cédule lors d'une transaction → problème administratif à la signature notaire → retard/annulation. Le courtier doit vérifier ce point en amont.$QK$,
TRUE),

('hypotheque','H016','Hypothèque — Valeur locative','single',
$QK$Le concept de VALEUR LOCATIVE (Eigenmietwert) en Suisse : qu'est-ce et impact fiscal ?$QK$,
$QK$["Un impôt sur l'immobilier", "Revenu FICTIF imposé au propriétaire occupant lui-même son bien. La valeur locative représente ce qu'il paierait en loyer s'il louait. Généralement 60-70% du loyer marché. Ajoutée au revenu imposable → augmente l'impôt sur le revenu. En contrepartie, les intérêts hypothécaires et frais d'entretien sont déductibles.", "Un abattement fiscal", "Interdite depuis 2020"]$QK$::jsonb,
1,
$QK$Valeur locative = spécificité suisse. Le propriétaire occupant paie de l'impôt sur un revenu qu'il ne perçoit pas réellement. En contrepartie, il déduit intérêts + entretien. Système souvent NEUTRE ou légèrement FAVORABLE au propriétaire endetté ; DÉFAVORABLE au propriétaire ayant fini d'amortir (VL imposée sans déduction significative). RÉFORME EN COURS depuis 2024 : possible abolition — à suivre.$QK$,
$QK$["Faux — c'est un revenu fictif, pas un impôt.", null, "Faux — c'est l'inverse.", "Faux — toujours en vigueur, projet d'abolition en discussion."]$QK$::jsonb,
$QK$Erreur = ne pas anticiper avec le client l'impact de la VL sur sa fiscalité annuelle → il découvre 2-5k CHF/an d'impôt supplémentaire. Devoir courtier = simuler la fiscalité globale AVANT achat.$QK$,
TRUE),

('hypotheque','H017','Hypothèque — Régime matrimonial','single',
$QK$Un couple marié sous régime de la participation aux acquêts achète une maison à 50/50. En cas de divorce, comment le bien est-il partagé ?$QK$,
$QK$["50/50 automatique", "Analyse : bien enregistré à 50/50 → chacun est propriétaire de sa quote-part. La liquidation fait la balance des apports (bien propre vs acquêt) → le conjoint qui a mis un apport en biens propres peut avoir un droit renforcé. La valeur des acquêts (dont plus-value du bien pendant le mariage) est partagée 50/50.", "Toujours à celui qui gagne le plus", "Le juge décide sans règle"]$QK$::jsonb,
1,
$QK$Régime participation aux acquêts (régime légal) = 4 masses : bien propre lui + bien propre elle + acquêts lui + acquêts elle. Le bien immobilier peut être détenu partiellement en biens propres (héritage, donation, avant mariage) et partiellement en acquêts (achat post-mariage). Liquidation complexe = souvent avocat obligatoire. Le régime de SÉPARATION DE BIENS simplifie tout.$QK$,
$QK$["Trop simpliste — les apports individuels comptent.", null, "Faux — pas de règle de revenu.", "Faux — le juge applique le droit."]$QK$::jsonb,
$QK$Erreur = ne pas conseiller un couple d'anticiper le régime matrimonial (contrat de mariage possible avant achat immobilier). Divorce → conflits + frais + perte d'énergie. Devoir de conseil élargi à l'aspect matrimonial.$QK$,
TRUE),

('hypotheque','H018','Hypothèque — Succession','single',
$QK$Un propriétaire décède. Que devient l'hypothèque ?$QK$,
$QK$["Elle disparaît automatiquement", "Elle est transmise aux HÉRITIERS avec le bien (le passif suit l'actif). Les héritiers peuvent : (1) accepter et continuer les remboursements, (2) vendre le bien pour rembourser, (3) répudier la succession si le passif > actif. La banque peut demander des garanties supplémentaires ou renégocier si les héritiers ne présentent pas les mêmes garanties.", "Elle est intégralement remboursée par l'assurance", "Les héritiers doivent la rembourser immédiatement"]$QK$::jsonb,
1,
$QK$Principe succession = transmission actif + passif. L'hypothèque suit le bien. Les héritiers deviennent débiteurs solidaires. Options : accepter, vendre, répudier (dans les 3 mois). La banque peut vérifier la solvabilité des nouveaux débiteurs et éventuellement demander des garanties. Certains clients souscrivent une ASSURANCE-VIE DÉCÈS pour couvrir la dette hypothécaire = protection famille très pertinente si un seul revenu supporte le crédit.$QK$,
$QK$["Faux — l'hypothèque suit le bien.", null, "Faux — sauf si le défunt avait une assurance décès couvrant la dette.", "Faux — pas d'exigibilité immédiate, sauf refus banque."]$QK$::jsonb,
$QK$Erreur = ne pas proposer d'assurance décès couvrant l'hypothèque à une famille mono-revenu → décès du soutien → conjoint survivant doit vendre en catastrophe. Le devoir de conseil hypothèque inclut la protection décès.$QK$,
TRUE),

('hypotheque','H019','Hypothèque — Assurance ECA','single',
$QK$L'assurance BÂTIMENT (ECA en Suisse) est-elle obligatoire ?$QK$,
$QK$["Non", "OUI dans la plupart des cantons — l'ECA (Établissement Cantonal d'Assurance) est un monopole d'État dans 19 cantons. Assurance incendie et éléments naturels obligatoire, prime = valeur d'assurance du bâtiment × taux (0,05-0,3‰). Dans quelques cantons (GE, VS, VD partiellement) : assurance privée obligatoire. Toujours obligatoire, opérateur variable.", "Optionnelle", "Uniquement pour les banques"]$QK$::jsonb,
1,
$QK$Assurance bâtiment (incendie + éléments naturels) = obligatoire dans toute la Suisse. Opérateur = ECA cantonal (monopole d'État) dans la plupart des cantons romands sauf GE et VS où c'est concurrentiel. Cette assurance ne couvre PAS : dégâts d'eau internes (à souscrire séparément), casse de vitres, RC propriétaire, dommages naturels non-couverts. Il faut donc COMPLÉTER par une assurance BÂTIMENT COMPLÉMENTAIRE et une RC PROPRIÉTAIRE.$QK$,
$QK$["Faux — obligation légale.", null, "Faux — obligation cantonale.", "Faux — obligation pour le propriétaire, pas pour la banque."]$QK$::jsonb,
$QK$Erreur = ne pas expliquer au propriétaire les lacunes ECA → sinistre eau non couvert → 30-100k CHF de dégâts à sa charge. Devoir courtier = liste des assurances complémentaires à souscrire dès l'achat.$QK$,
TRUE),

('hypotheque','H020','Hypothèque — Forward rate','single',
$QK$Un client a une hypothèque taux fixe à 2,3% arrivant à échéance dans 14 mois. Les taux actuels sont à 3,1%. Solution "forward" ?$QK$,
$QK$["Impossible", "Le FORWARD RATE permet de BLOQUER aujourd'hui un taux pour un renouvellement dans 14 mois. La banque facture une prime (~10-30 bps sur le taux) en échange de la garantie. Utile si on anticipe une hausse des taux. Si les taux baissent finalement, on est coincé au forward — c'est un pari.", "Le client doit attendre", "Uniquement pour les entreprises"]$QK$::jsonb,
1,
$QK$Forward rate = engagement à terme (0-24 mois avant échéance) sur un nouveau taux hypothécaire. Prime typique : 5-30 bps par mois d'attente ajoutée. Utile pour éliminer le risque de hausse pendant la période transitoire. INCONVÉNIENT : si les taux baissent, on paie la prime + le taux bloqué plus haut → pari perdant. Analyse à faire : sensibilité budget du client à une hausse vs coût de la protection.$QK$,
$QK$["Faux — outil courant.", null, "Faux — le forward est justement l'outil pour NE PAS attendre.", "Faux — accessible particuliers."]$QK$::jsonb,
$QK$Erreur = ne pas mentionner le forward à un client anxieux face à la hausse des taux → 12 mois plus tard il paie 60-100 bps de plus. Devoir informatif au minimum.$QK$,
TRUE),

('hypotheque','H021','Hypothèque — SARON','single',
$QK$Comment fonctionne concrètement le renouvellement d'une hypothèque SARON ?$QK$,
$QK$["Renouvellement automatique tous les 10 ans", "Le taux est CALCULÉ tous les 1-3 mois selon la période choisie (1M, 3M, 6M SARON) sur la base du SARON moyen de la période + marge banque fixe. Il n'y a pas de 'renouvellement' formel — l'hypothèque est indexée en continu. Client peut résilier à chaque période de refixation.", "Taux fixe à vie", "Renouvellement annuel manuel"]$QK$::jsonb,
1,
$QK$SARON = Swiss Average Rate Overnight (remplaçant du LIBOR CHF depuis 2022). Hypothèque SARON = taux indexé sur SARON moyen (1M, 3M, 6M au choix) + marge banque fixe (0,7-1,2% en principe). À chaque période de refixation, le nouveau taux s'applique automatiquement. Résiliation possible à chaque échéance de refixation (grande flexibilité). Convient aux clients tolérants au risque de hausse.$QK$,
$QK$["Faux — refixation périodique.", null, "Faux — c'est justement variable.", "Faux — automatique par refixation."]$QK$::jsonb,
$QK$Erreur = client qui pense être sur "taux fixe" alors qu'il est SARON → surprise à la 1re hausse → défaut budgétaire. Devoir courtier = expliquer le mécanisme AVANT signature.$QK$,
TRUE),

('hypotheque','H022','Hypothèque — Financement construction','single',
$QK$Financement d'une CONSTRUCTION neuve (pas achat existant) : particularité ?$QK$,
$QK$["Identique à un achat", "Le prêt est débloqué par TRANCHES au fil de l'avancement des travaux (crédit de construction), et non en une fois. Chaque tranche déclenche des intérêts INTERMÉDIAIRES calculés sur le montant déjà versé. Une fois la construction achevée et validée par expertise, le crédit de construction se transforme en hypothèque définitive. Taux intermédiaire souvent > taux hypothèque finale.", "Financement 100% avant construction", "Financement uniquement après achèvement"]$QK$::jsonb,
1,
$QK$Crédit de construction = phase transitoire spécifique. Déblocages progressifs (fondations, gros œuvre, second œuvre, achèvement) au fil des factures de l'entreprise. Client paie des intérêts intermédiaires calculés sur les tranches déjà versées, mois par mois. Une fois construction terminée + attestation architecte + estimation finale → crédit consolidé en hypothèque long terme (fixe ou SARON). Prévoir 6-12 mois de trésorerie intérêts intermédiaires.$QK$,
$QK$["Faux — mécanisme spécifique.", null, "Faux — pas de préfinancement 100%.", "Faux — c'est en cours de construction."]$QK$::jsonb,
$QK$Erreur = ne pas anticiper les intérêts intermédiaires → client court de trésorerie pendant construction → retards chantier → cascade problèmes. Devoir courtier = simulation cash-flow période construction complète.$QK$,
TRUE),

('hypotheque','H023','Hypothèque — Impôt anticipé','single',
$QK$Un client rembourse ses intérêts hypothécaires. Y a-t-il un impôt ANTICIPÉ prélevé sur ces paiements ?$QK$,
$QK$["Oui, 35%", "Non — l'impôt anticipé s'applique aux intérêts REÇUS (par le déposant sur son compte), pas aux intérêts PAYÉS (par l'emprunteur sur son crédit). L'emprunteur déduit ses intérêts payés de son revenu imposable, sans impôt anticipé.", "Oui, 15%", "Uniquement dans certains cantons"]$QK$::jsonb,
1,
$QK$Confusion fréquente. Impôt anticipé 35% = prélevé par la banque sur les INTÉRÊTS que le client PERÇOIT de son compte épargne (récupérable via déclaration fiscale). Sur les intérêts hypothécaires PAYÉS par l'emprunteur : pas d'impôt anticipé. L'emprunteur DÉDUIT au contraire ces intérêts de son revenu imposable → économie fiscale nette.$QK$,
$QK$["Faux — c'est l'inverse.", null, "Faux — pas d'impôt anticipé sur intérêts payés.", "Faux — règle fédérale uniforme."]$QK$::jsonb,
$QK$Erreur = expliquer à tort un impôt anticipé sur les intérêts payés → client s'imagine payer 35% d'impôt supplémentaire → confusion + perte de crédibilité conseiller.$QK$,
TRUE),

('hypotheque','H024','Hypothèque — Fortune','single',
$QK$Un couple achète une maison 1,2 M CHF avec 80% d'hypothèque. Impact sur leur impôt sur la fortune ?$QK$,
$QK$["Ils paient impôt sur 1,2 M CHF de fortune", "Ils paient impôt sur la VALEUR FISCALE du bien − la dette hypothécaire (960 000). Souvent la valeur fiscale est ≈ 60-80% de la valeur d'achat selon canton. Ex : valeur fiscale 800k − hypothèque 960k = fortune imposable NÉGATIVE sur ce bien (report sur autres actifs). Résultat : souvent l'immobilier hypothéqué RÉDUIT l'impôt sur la fortune globale.", "Ils sont exonérés", "Uniquement 50% imposé"]$QK$::jsonb,
1,
$QK$Impôt sur la fortune = actif net (valeur fiscale immobilier + comptes + titres + autres − dettes). L'hypothèque est DÉDUITE de la fortune brute. Souvent la valeur fiscale de l'immobilier < valeur d'achat (60-80% selon canton). Résultat : un immobilier fortement hypothéqué peut RÉDUIRE l'assiette fortune totale. Point positif fiscal peu connu — argument commercial pertinent en conseil.$QK$,
$QK$["Faux — dette hypothécaire déductible.", null, "Faux — pas d'exonération complète.", "Faux — 100% déductible."]$QK$::jsonb,
$QK$Erreur = client qui redoute une explosion de son impôt fortune en achetant → il abandonne un projet rentable à cause d'une méconnaissance fiscale. Devoir informatif du courtier.$QK$,
TRUE),

('hypotheque','H025','Hypothèque — Plus-value','single',
$QK$Un propriétaire revend son bien 15 ans après achat, avec plus-value de 400k CHF. Fiscalité ?$QK$,
$QK$["Aucun impôt", "Impôt sur les GAINS IMMOBILIERS (IGI) cantonal, TAUX DÉGRESSIF selon durée de détention. Après 15 ans : dégressif fort (souvent 15-25% de la plus-value au lieu de 30-40% en cas de revente précoce). Certains cantons EXONÈRENT partiellement l'IGI pour la résidence principale si REMPLOI dans un nouvel achat dans les 2 ans.", "Impôt 40% sur la plus-value", "Uniquement sur les non-résidents"]$QK$::jsonb,
1,
$QK$Impôt sur les gains immobiliers (IGI) = cantonal, dégressif selon durée de détention (généralement > 20 ans = quasi nul). Résidence principale : remploi possible dans les 2 ans → exonération/report d'imposition. Point crucial : optimiser le moment de la vente + envisager le remploi. Sur 400k de plus-value, l'écart entre imposition immédiate et remploi peut être de 40-100k CHF.$QK$,
$QK$["Faux — impôt significatif.", null, "Sur-estime à long terme.", "Faux — s'applique aux résidents."]$QK$::jsonb,
$QK$Erreur = client qui revend rapidement sans anticiper l'IGI → surprise fiscale → parfois obligé de conserver le bien 2-3 ans de plus pour ne pas être perdant. Devoir informatif AVANT vente.$QK$,
TRUE),

('hypotheque','H026','Hypothèque — Entretien déductible','single',
$QK$Le propriétaire fait 30k CHF de travaux sur sa maison. Tous les frais sont-ils déductibles ?$QK$,
$QK$["Oui tous", "Distinction FISCALE cruciale : (1) TRAVAUX D'ENTRETIEN (maintenir en état — peinture, réparations, remplacement à l'identique) = déductibles du revenu imposable l'année du paiement. (2) TRAVAUX PLUS-VALUE (améliorations — extension, cuisine neuve haut de gamme, transformation) = NON déductibles du revenu mais ajoutés au prix d'achat pour réduire l'IGI à la revente.", "Rien n'est déductible", "50 % déductibles"]$QK$::jsonb,
1,
$QK$Distinction fiscale MAJEURE. Entretien (maintenir état) = déductible du revenu, imputation immédiate. Plus-value (améliorer) = capitalisé sur le prix d'achat, économie à la revente uniquement. Zone grise (par ex : cuisine remplacée par équivalent moderne) = arbitrage administratif. Conseil : conserver TOUTES les factures avec description précise (entretien vs plus-value) — sinon le fisc requalifie souvent en plus-value (défavorable).$QK$,
$QK$["Faux — distinction cruciale.", null, "Faux — l'entretien est déductible.", "Faux — 100% ou 0% selon nature."]$QK$::jsonb,
$QK$Erreur = client mélange entretien et plus-value dans ses factures → perte fiscale immédiate + moins d'imputation à la revente. Point à connaître pour conseil global patrimonial.$QK$,
TRUE),

('hypotheque','H027','Hypothèque — Assurance décès','single',
$QK$Un couple mono-revenu achète 1M CHF avec 800k d'hypothèque. Assurance recommandée pour couvrir la dette en cas de décès du soutien ?$QK$,
$QK$["Pas nécessaire", "Assurance décès TEMPORAIRE (Term Life) sur le soutien de famille, capital décès = montant de l'hypothèque (800k), durée = durée du plan d'amortissement (généralement 15-25 ans), capital dégressif possible pour suivre l'amortissement. Prime modique (200-800 CHF/an selon âge/santé) pour éviter que la famille perde la maison en cas de décès prématuré.", "Assurance-vie mixte 800k", "Assurance-vie 3a"]$QK$::jsonb,
1,
$QK$Assurance décès temporaire (pur risque) = produit essentiel pour couples mono-revenu avec dette. Le capital est versé aux héritiers/conjoint pour rembourser la dette. Alternatives : (1) assurance-vie mixte plus chère (mélange épargne+risque, inutile ici), (2) déjà couvert par LPP décès si suffisant. Analyse : quel serait le gap entre les rentes survivants LPP + AVS et le coût maintien de la maison sans le revenu du défunt ? Ce gap = capital décès à souscrire.$QK$,
$QK$["Faute grave — famille pourrait perdre la maison.", null, "Sur-équipement — l'épargne est mieux ailleurs.", "3a limité à 7 056/an, pas suffisant pour couvrir 800k dette."]$QK$::jsonb,
$QK$Erreur = ne pas proposer l'assurance décès à un couple mono-revenu = manquement au devoir de protection famille. Le survivant se retrouve à devoir vendre en catastrophe. Cas classique d'action en défaut de conseil.$QK$,
TRUE),

('hypotheque','H028','Hypothèque — Devises','single',
$QK$Peut-on emprunter en EUR pour acheter en Suisse afin de profiter de taux plus bas ?$QK$,
$QK$["Oui, avantageux", "Techniquement possible mais TRÈS RISQUÉ pour un résident suisse à revenu en CHF : le risque de change peut anéantir l'écart de taux. Si CHF se renforce (+10-15%), la dette en EUR se GONFLE en valeur CHF, dépassant largement les économies d'intérêts. Depuis 2015 (choc suppression plancher EUR/CHF), les banques suisses N'OFFRENT PLUS ce type de crédit hypothécaire pour résidents.", "Uniquement pour non-résidents", "Interdit par la loi"]$QK$::jsonb,
1,
$QK$Hypothèque en devises pour résident CHF = mécanique déconseillée. Rare en pratique aujourd'hui. Le risque de change est structurellement asymétrique : le CHF a tendance à s'apprécier sur long terme (valeur refuge), donc dette EUR devient plus coûteuse en CHF. Les banques suisses ont massivement retiré ces produits après 2015. Si proposé, c'est un signal d'alerte MAJEUR de mauvais conseil.$QK$,
$QK$["Faux — risque de change massif.", null, "Faux — surtout pour résidents.", "Faux — pas d'interdiction légale, retrait commercial."]$QK$::jsonb,
$QK$Erreur = envisager sérieusement une hypothèque EUR pour un client CHF → risque de créer une exposition dangereuse. À déconseiller catégoriquement.$QK$,
TRUE),

('hypotheque','H029','Hypothèque — Amortissement anticipé','single',
$QK$Un client rembourse par avance 100k CHF sur son hypothèque taux fixe 10 ans (7 ans restants). Conséquences ?$QK$,
$QK$["Aucune pénalité", "PÉNALITÉ D'AMORTISSEMENT ANTICIPÉ selon la banque : (1) certaines banques autorisent 10-20% du capital initial par an sans pénalité, (2) au-delà, pénalité = manque à gagner banque (taux hypothèque − taux placement banque sur durée résiduelle × montant × années restantes), souvent 5-15% du montant remboursé. À NÉGOCIER dans le contrat initial.", "Récompense de 5%", "Impossible"]$QK$::jsonb,
1,
$QK$Amortissement anticipé partiel = souvent limité par contrat. Beaucoup de banques autorisent 10-20% du capital initial/an sans pénalité (à négocier à la signature). Au-delà, pénalité de "manque à gagner". Attention : les hypothèques SARON permettent l'amortissement à chaque échéance de refixation sans pénalité, contrairement au fixe. Point à intégrer au choix taux fixe/SARON.$QK$,
$QK$["Faux — pénalité fréquente.", null, "Faux — pas de bonus.", "Faux — c'est possible, avec conditions."]$QK$::jsonb,
$QK$Erreur = client qui reçoit un héritage et veut rembourser sans vérifier les pénalités → 10-20k CHF de pénalité imprévue. Devoir courtier = clarifier ces clauses à la signature initiale.$QK$,
TRUE),

('hypotheque','H030','Hypothèque — Renégociation','single',
$QK$Les taux ont fortement baissé, un client a une hypothèque à 3,5% avec 6 ans restants. Peut-il "renégocier" ?$QK$,
$QK$["Oui, gratuitement", "Renégocier en cours de contrat = résilier + prendre un nouveau contrat, ce qui déclenche la PÉNALITÉ DE SORTIE ANTICIPÉE (manque à gagner banque). Calcul : (3,5% − taux marché résiduel) × capital × 6 ans. Souvent 30-80k CHF sur un prêt de 500k. Alternative : proposition BLEND & EXTEND (mix moyen + prolongation) parfois acceptée par la banque sans pénalité pleine.", "Impossible", "Uniquement à échéance"]$QK$::jsonb,
1,
$QK$Renégociation en cours de fixe = coûteuse. Le BLEND & EXTEND est une technique où la banque accepte un nouveau contrat prolongé combinant l'ancien taux (moyenne pondérée) + nouveau taux → pas de pénalité pleine, mais taux résultant moyen. Analyse rentabilité à faire : coût pénalité vs économie d'intérêts sur la période restante + le nouveau contrat.$QK$,
$QK$["Faux — pénalité importante.", null, "Faux — négociation possible.", "Faux — négociable avant échéance, avec conditions."]$QK$::jsonb,
$QK$Erreur = client qui renégocie sans calcul précis → pénalité supérieure à l'économie attendue → perte nette. Devoir courtier = simulation chiffrée avec/sans blend & extend.$QK$,
TRUE),

('hypotheque','H031','Hypothèque — Rachat par une autre banque','single',
$QK$Un client veut transférer son hypothèque de la banque X vers la banque Y qui offre un meilleur taux. Faisable ?$QK$,
$QK$["Non", "Possible mais complexe : le transfert nécessite le remboursement anticipé chez X (déclenche pénalité) + nouveau contrat chez Y. Attention aussi aux frais de cession de cédule + éventuels frais administratifs. À CHIFFRER : gain d'intérêts sur la durée résiduelle − pénalité chez X − frais notaire. Rentable seulement si écart de taux > 40-60 bps ET durée résiduelle > 3 ans généralement.", "Oui gratuitement", "Uniquement à échéance"]$QK$::jsonb,
1,
$QK$Transfert d'hypothèque = techniquement possible mais rarement rentable à cause des pénalités de sortie du taux fixe existant. Économiquement pertinent uniquement dans des cas précis : (1) écart de taux important > 50 bps, (2) durée résiduelle > 3 ans, (3) faibles frais annexes. Le courtier compétent fait le CALCUL COMPARATIF précis avant recommandation.$QK$,
$QK$["Faux — technique existe.", null, "Faux — jamais gratuit en présence de taux fixe.", "Faux — négociation possible à d'autres moments."]$QK$::jsonb,
$QK$Erreur = pousser un client à changer de banque sans avoir calculé la pénalité → il perd de l'argent net. Ou à l'inverse, ne pas envisager le transfert quand c'est rentable → perte d'économie évitable.$QK$,
TRUE),

('hypotheque','H032','Hypothèque — Location Airbnb','single',
$QK$Un propriétaire loue une partie de sa résidence principale sur Airbnb (revenu 15k CHF/an). Implications hypothécaires ?$QK$,
$QK$["Aucune", "À DÉCLARER À LA BANQUE : la location partielle peut requalifier la nature du bien (résidence principale pure vs mixte). Certaines banques exigent une notification et potentiellement une adaptation du contrat. Fiscalement, les revenus Airbnb sont IMPOSABLES comme revenu, tandis que les intérêts hypothécaires restent déductibles proportionnellement. Aussi : LEX WEBER peut interdire toute location saisonnière dans certaines communes.", "Interdit", "Aucune obligation fiscale"]$QK$::jsonb,
1,
$QK$Location partielle d'une résidence principale (Airbnb, chambres d'hôtes) = à déclarer à la banque prêteuse (obligation de notification). Fiscalement, revenus imposables + intérêts hypothécaires proportionnels déductibles. En zone LEX WEBER (communes touristiques), la location saisonnière peut être restreinte. Il faut aussi une assurance RC PROPRIÉTAIRE ÉTENDUE (les CGA classiques excluent souvent la location touristique).$QK$,
$QK$["Faux — plusieurs implications.", null, "Faux — pas interdit sauf zones spécifiques.", "Faux — revenus imposables."]$QK$::jsonb,
$QK$Erreur = client qui loue Airbnb sans notifier la banque + sans adapter son assurance → sinistre (dégât d'un locataire) → refus indemnisation + potentielle mise en demeure banque.$QK$,
TRUE),

('hypotheque','H033','Hypothèque — Copropriété','single',
$QK$Un client achète un appartement en copropriété (PPE). Différences avec une maison individuelle ?$QK$,
$QK$["Aucune", "PPE = Propriété par étages. Le client possède : (1) SA quote-part de propriété du terrain + parties communes, (2) DROIT EXCLUSIF sur son appartement (parties privatives). Charges de copropriété obligatoires (fonds de rénovation, entretien commun). Fiscalement, on impose la QUOTE-PART. Décisions importantes prises en ASSEMBLÉE (majorité qualifiée pour rénovations). L'hypothèque porte sur la quote-part uniquement.", "Le client possède tout l'immeuble", "Statut de locataire"]$QK$::jsonb,
1,
$QK$PPE (Propriété par étages, art. 712a CC) = régime spécial. Points clés : (1) charges copropriété mensuelles/annuelles, (2) fonds de rénovation obligatoire, (3) règles de vote pour rénovations, (4) impact du règlement de PPE sur usage du bien. Analyse à faire AVANT achat : montant du fonds de rénovation actuel, planning gros travaux prévus, conflits d'assemblée existants. Un fonds sous-doté avec toiture à refaire = signal d'alerte.$QK$,
$QK$["Faux — 2 régimes juridiques différents.", null, "Faux — propriété partagée.", "Faux — vraie propriété."]$QK$::jsonb,
$QK$Erreur = ne pas analyser l'état de la copropriété avant achat → client découvre après 6 mois qu'il doit verser 30k CHF pour la toiture. Devoir de conseil élargi à l'analyse du dossier PPE.$QK$,
TRUE),

('hypotheque','H034','Hypothèque — Frais notaire','single',
$QK$Qui choisit le notaire pour la signature d'un achat immobilier en Suisse ?$QK$,
$QK$["Uniquement le vendeur", "Généralement l'ACHETEUR choisit le notaire, sauf accord contraire. Le notaire est un TIERS impartial garant de la sécurité juridique de l'acte. Ses frais sont réglementés au tarif cantonal (tarif d'honoraires notariaux). Habituellement à la charge de l'acheteur (mais négociable). Bien choisir un notaire expérimenté en transactions immobilières.", "La banque", "Un notaire commun obligatoire"]$QK$::jsonb,
1,
$QK$Notaire = choisi par l'acheteur en principe. Tarif d'honoraires notariaux cantonal (souvent 0,5-1% du prix). Frais à la charge de l'acheteur (usage) sauf accord contraire. Point à négocier avec le vendeur si le marché est très favorable à l'acheteur. Rôle notaire : rédiger l'acte de vente, vérifier statut foncier, calculer et prélever les droits de mutation, coordonner l'inscription au registre foncier.$QK$,
$QK$["Faux — l'acheteur en principe.", null, "Faux — c'est notarial.", "Faux — mais possible commun accord."]$QK$::jsonb,
$QK$Erreur = ne pas guider le client sur le choix du notaire → notaire inexpérimenté → erreurs à la signature. Recommandation d'un notaire compétent = valeur ajoutée du courtier.$QK$,
TRUE),

('hypotheque','H035','Hypothèque — Coopérative d''habitation','single',
$QK$Une coopérative d'habitation propose au client de devenir "sociétaire" avec versement de 40 000 CHF de parts sociales pour un loyer modéré à vie. Le 3a EPL est-il utilisable ?$QK$,
$QK$["Non", "OUI — art. 30c LPP et art. 3 al. 3 OPP3 : le retrait EPL peut financer l'acquisition de PARTS SOCIALES d'une coopérative d'habitation à but non lucratif, si le logement est à usage personnel principal. Même mécanisme fiscal (imposition prestation en capital) + remboursement obligatoire si sortie de la coopérative.", "Uniquement pour l'achat", "Uniquement 50%"]$QK$::jsonb,
1,
$QK$Cas peu connu mais utile : l'EPL couvre l'achat de parts de coopérative d'habitation, à condition d'occuper le logement à titre principal. Solution intéressante pour les jeunes actifs qui veulent un logement stable sans acheter directement (Zurich, Bâle notamment). Sortie de la coopérative = remboursement EPL obligatoire, comme pour une vente immobilière classique.$QK$,
$QK$["Faux — c'est autorisé.", null, "Sous-évalue — les 2 sont éligibles.", "Faux — 100% éligible."]$QK$::jsonb,
$QK$Erreur = refuser un projet coopérative en pensant que EPL est réservé à l'achat privé → client rate une bonne option (loyers 30-40% moins chers qu'un locatif standard).$QK$,
TRUE)

ON CONFLICT DO NOTHING;
