-- ═════════════════════════════════════════════════════════
-- Klary — Seed Prévoyance v2 : +25 questions techniques
--   • 3a technique (nantissement, allocation, bénéficiaires, divorce)
--   • Incapacité gain / invalidité / AI / LAA (coordination)
--   • Assurance-vie détail (types, réserve, valeur rachat)
--   • Rentes vs capital à la retraite
--   • AVS21 et actualité 2026
-- ═════════════════════════════════════════════════════════

INSERT INTO training_questions
  (module_key, external_id, category, question_type, question, options, correct, explanation, why_wrong, consequence, active) VALUES

('prevoyance','P011','3a — Nantissement','single',
$QK$Le 3a peut être NANTI en garantie d'une hypothèque. Que signifie concrètement ce nantissement ?$QK$,
$QK$["Le capital 3a est retiré et versé à la banque", "Le capital 3a reste chez l'institution 3a mais est bloqué en garantie du prêt : la banque a un droit de gage. Aucune imposition (pas de retrait), pas de perte de rendement 3a, mais impossibilité de retirer ou modifier le compte sans accord banque.", "Le 3a devient propriété de la banque", "Aucun effet sur le 3a"]$QK$::jsonb,
1,
$QK$Nantissement = droit de gage sur le capital 3a, sans transfert. Le 3a continue de générer des intérêts/rendement, mais est bloqué comme garantie. Utilisé pour l'amortissement indirect du 2ᵉ rang hypothécaire : gain fiscal double (déduction 3a + intérêts hypothécaires déductibles sur dette non amortie).$QK$,
$QK$["FAUX — nantissement ≠ retrait. Pas d'imposition en nantissement.", null, "FAUX — droit de gage seulement, propriété reste au client.", "FAUX — impact opérationnel (blocage modifications) réel."]$QK$::jsonb,
$QK$Erreur = client qui pense pouvoir retirer son 3a nanti pour un autre projet → refus banque, colère. Le nantissement est une décision qui doit être expliquée en amont avec ses contraintes.$QK$,
TRUE),

('prevoyance','P012','3a — Titres vs compte','single',
$QK$Un client de 35 ans compare un 3a "compte épargne" (0,5% de rendement) vs un 3a "titres" (fonds actions à 4-6% attendu sur long terme). Que privilégier ?$QK$,
$QK$["Toujours compte épargne — sécurité", "Toujours titres — rendement plus haut", "Analyse selon horizon + tolérance risque : 3a titres pertinent si horizon > 10 ans (lisse la volatilité) ET tolérance perte temporaire 20-30%. Sinon compte épargne pour la partie sécurisée. Certains clients font un mix 60/40.", "Peu importe, c'est le même montant"]$QK$::jsonb,
2,
$QK$Différentiel de rendement 3,5-5,5%/an sur 30 ans = capital final ×2 à ×3. Mais volatilité titres = perte temporaire possible jusqu'à −30%. Décision selon : (1) horizon (>10 ans pour absorber volatilité), (2) tolérance émotionnelle aux baisses, (3) autres actifs déjà exposés. Un 3a titres est le choix quasi-toujours gagnant pour un moins de 45 ans.$QK$,
$QK$["Trop sécurisé — sous-optimisation majeure sur horizon long.", "Trop risqué — un client à 3 ans de retraite ne doit pas être en titres.", null, "Faux — les 2 produits diffèrent radicalement dans le rendement final."]$QK$::jsonb,
$QK$Erreur = laisser un client 30 ans sur un 3a compte pendant 30 ans → capital final 60k CHF au lieu de 130-160k CHF possibles. Le courtier compétent introduit la question de l'allocation dès l'ouverture.$QK$,
TRUE),

('prevoyance','P013','3a — Bénéficiaires','single',
$QK$Ordre légal des bénéficiaires 3a en cas de décès (art. 2 OPP3) — ordre STRICT dans lequel le capital doit être versé si aucune désignation particulière ?$QK$,
$QK$["Uniquement le conjoint", "1) Conjoint / partenaire enregistré ; 2) Descendants directs (enfants) + concubin sous conditions ; 3) Parents ; 4) Frères et sœurs ; 5) Autres héritiers légaux", "Toujours 50% conjoint / 50% enfants", "L'ordre est libre"]$QK$::jsonb,
1,
$QK$Art. 2 OPP3 : ordre STRICT et IMPÉRATIF. Groupe 1 = conjoint/partenaire enregistré → si aucun, groupe 2 = descendants directs (avec concubin sous conditions ≥5 ans cohabitation + désignation) → groupe 3 = parents → groupe 4 = frères et sœurs → groupe 5 = autres héritiers légaux. Chaque groupe exclut les suivants. Le client peut affiner la répartition DANS un groupe (par ex. entre les enfants), pas changer l'ordre.$QK$,
$QK$["Faux — plusieurs groupes possibles.", null, "FAUX — l'ordre exclut les suivants, pas de partage automatique.", "FAUX — l'ordre est légal et strict, pas modifiable."]$QK$::jsonb,
$QK$Erreur = client qui pense pouvoir désigner son ami comme bénéficiaire 3a → refus institution 3a → capital versé à des membres de famille éloignés qu'il n'aimait pas. Devoir de conseil = expliquer les limites de la désignation 3a.$QK$,
TRUE),

('prevoyance','P014','3a — Divorce','single',
$QK$Un couple divorce. Comment le 3a acquis pendant le mariage est-il traité dans la liquidation ?$QK$,
$QK$["Il reste 100% au titulaire", "Le 3a est intégré à la LIQUIDATION du régime matrimonial (comme tout élément d'épargne acquis pendant le mariage sous régime légal de la participation aux acquêts). Partage 50/50 de la valeur acquise pendant le mariage, sauf convention matrimoniale différente.", "Il est toujours partagé 50/50 quel que soit le régime", "Le juge décide arbitrairement"]$QK$::jsonb,
1,
$QK$Régime légal suisse = participation aux acquêts. Les 3a et 3b acquis pendant le mariage sont des ACQUÊTS → partagés 50/50 en valeur à la dissolution. Les 3a acquis avant le mariage restent des biens propres. Distinction TRÈS différente du 2e pilier LPP qui a sa propre règle de partage (art. 122-124 CC : partage prévoyance).$QK$,
$QK$["Faux — le 3a est un acquêt partagé.", null, "Sur-simplification — le régime matrimonial (séparation de biens vs acquêts vs communauté) change la règle.", "Faux — le juge applique le droit, pas d'arbitraire."]$QK$::jsonb,
$QK$Erreur = client mal informé qui pense garder son 3a intact en divorce → contentieux + frais avocat + surprise mauvaise. Devoir courtier = pour un client à la fois marié et souscripteur 3a important, mentionner l'implication en cas de divorce.$QK$,
TRUE),

('prevoyance','P015','3a — Fiscalité successorale','single',
$QK$Un titulaire d'un 3a décède, laissant 200k CHF sur ce compte. Ses enfants héritent. Fiscalement, comment le capital est-il traité ?$QK$,
$QK$["Aucun impôt", "Imposition SÉPARÉE du revenu ordinaire, chez le BÉNÉFICIAIRE, au taux réduit des prestations en capital de prévoyance. Impôt fédéral + cantonal + communal, ≈ 4-12% selon canton et montant. + potentiellement droits de succession selon parenté et canton.", "Impôt au taux marginal chez le bénéficiaire", "Impôt de 50% forfaitaire"]$QK$::jsonb,
1,
$QK$Prestation 3a versée aux bénéficiaires en cas de décès = imposition séparée au taux préférentiel de la prestation en capital de prévoyance (barème dégressif). En plus, potentiels droits de succession cantonaux selon lien de parenté (souvent 0% pour descendants directs mais >20% pour tiers, selon canton).$QK$,
$QK$["Faux — imposition existe.", null, "Faux — pas au marginal, taux réduit spécifique.", "Faux — pas 50% forfaitaire."]$QK$::jsonb,
$QK$Erreur = ne pas expliquer aux héritiers le régime fiscal → ils dépensent en croyant tout net d'impôt → sanction fiscale lourde. Devoir informatif du courtier.$QK$,
TRUE),

('prevoyance','P016','Incapacité de gain — LCA','single',
$QK$Un salarié tombe malade. Après combien de temps son EMPLOYEUR arrête-t-il de payer le salaire (obligation art. 324a CO) ?$QK$,
$QK$["Après 1 mois seulement", "Selon l'ANCIENNETÉ, échelle bernoise/vaudoise/zurichoise : 1re année d'engagement = 3 semaines de salaire, puis progression jusqu'à 6 mois pour ancienneté 20+ ans. AU-DELÀ, aucun salaire = LACUNE.", "Le salaire est payé à vie", "L'employeur paie 100% pendant 1 an"]$QK$::jsonb,
1,
$QK$Art. 324a CO + jurisprudence : l'employeur maintient le salaire un TEMPS LIMITÉ selon ancienneté, sauf convention plus favorable (CCT, contrat individuel, LCA perte de gain souscrite par l'employeur). Passé ce délai = lacune de revenu. L'AI ne verse qu'après 1 an d'incapacité. Entre les 2 = LACUNE CRITIQUE à couvrir par LCA "perte de gain maladie".$QK$,
$QK$["Faux — au moins 3 semaines même en 1re année.", null, "Faux — obligation limitée dans le temps.", "Faux — sauf LCA employeur ou CCT étendue."]$QK$::jsonb,
$QK$Erreur = client qui pense être couvert par son salaire "toujours" → il tombe malade, découvre à J+90 qu'il n'a plus de revenu, drame familial. LCA perte de gain maladie = produit fondamental à proposer systématiquement.$QK$,
TRUE),

('prevoyance','P017','Assurance accident — LAA','single',
$QK$Différence entre LAA obligatoire et LAA complémentaire (LCA accident) ?$QK$,
$QK$["Aucune", "LAA OBLIGATOIRE : couvre 80% du salaire jusqu'au plafond de 148 200 CHF/an (2026), toute personne salariée dès 8h/semaine. LAA COMPLÉMENTAIRE (LCA) : couvre les 20% manquants + le salaire au-dessus du plafond LAA + prestations hospitalières privées.", "LAA obligatoire couvre 100%", "LCA accident inutile"]$QK$::jsonb,
1,
$QK$LAA (Loi sur l'Assurance Accident) = obligatoire, prise en charge par l'employeur, couvre 80% du salaire assuré jusqu'au plafond légal (148 200 CHF/an en 2026). LCA accident = complémentaire, comble les 3 lacunes : (1) les 20% non couverts, (2) le salaire au-dessus du plafond LAA (souvent négligé pour hauts revenus), (3) division hospitalière privée en cas d'accident.$QK$,
$QK$["Faux — 2 mécaniques distinctes.", null, "Faux — 80% strict.", "Faux — LCA très pertinent pour hauts revenus."]$QK$::jsonb,
$QK$Erreur = un cadre à 200 000 CHF/an qui n'a que la LAA obligatoire → en cas d'accident invalidant, il touche 80% × 148 200 = 118 560 CHF/an, soit 41% de son vrai salaire. Perte massive évitable par LCA. Devoir courtier = alerter les hauts revenus systématiquement.$QK$,
TRUE),

('prevoyance','P018','Invalidité — Définitions','single',
$QK$Différence FONDAMENTALE entre "incapacité de travail" et "invalidité" ?$QK$,
$QK$["Aucune", "INCAPACITÉ DE TRAVAIL : temporaire, mesurée en % dans la profession actuelle, décidée par le médecin traitant. INVALIDITÉ : durable (min 1 an), mesurée par l'AI (10 offices AI), 40-100%, prise en compte de la capacité à exercer TOUTE profession raisonnablement exigible (pas seulement la sienne).", "Ce sont des synonymes", "Invalidité < incapacité"]$QK$::jsonb,
1,
$QK$Point CRITIQUE souvent confondu. Incapacité travail = clinique, décidée par médecin, souvent à court terme, dans le poste. Invalidité = juridique, décidée par l'AI après enquête, considère la capacité résiduelle sur le marché du travail suisse (pas juste dans sa profession). Beaucoup de médecins "incapacitent" à 100% des patients que l'AI reconnaît invalides à 40% seulement = énorme lacune.$QK$,
$QK$["Faux — 2 concepts totalement différents.", null, "Faux — c'est un contresens dangereux.", "Faux — les 2 sont indépendants."]$QK$::jsonb,
$QK$Erreur = agent qui explique "vous serez couvert par l'AI si vous êtes en arrêt de travail" = confusion grave. Beaucoup de clients découvrent 12-18 mois après leur maladie que l'AI les juge capables de travailler dans une autre profession → refus de rente → drame.$QK$,
TRUE),

('prevoyance','P019','AI — Délai carence','single',
$QK$Combien de temps entre le début d'une incapacité de gain durable et le début du versement d'une rente AI ?$QK$,
$QK$["Immédiatement", "Minimum 12 mois. L'AI n'octroie une rente qu'après ≥ 40% d'incapacité de gain pendant ≥ 1 an ininterrompu. Décision effective peut prendre 18-24 mois. LACUNE MAJEURE de revenu à combler par indemnité journalière maladie (LCA) + éventuellement LPP.", "6 mois", "3 mois"]$QK$::jsonb,
1,
$QK$Cascade : (1) Assurance maladie perte de gain (LCA) paie les 24 premiers mois. (2) LPP invalidité prend le relais à 24 mois (souvent 60% du salaire assuré). (3) AI verse rente à partir de 12 mois si dossier accepté (mais souvent traitement du dossier 12-24 mois supplémentaires). ENTRE l'événement et la 1ère rente AI = LACUNE 12-24 mois de revenu si pas de LCA.$QK$,
$QK$["Faux — délai légal minimum 12 mois.", null, "Faux — 12 mois minimum.", "Faux — 12 mois minimum."]$QK$::jsonb,
$QK$Erreur = laisser un indépendant sans LCA indemnités journalières → il tombe malade → 12 mois sans revenu → drame. Le courtier doit vérifier la couverture "période de carence" pour tout indépendant et pour tout salarié à revenu élevé.$QK$,
TRUE),

('prevoyance','P020','Coordination AI + LPP','single',
$QK$Un salarié invalide touche la rente AI + la rente LPP invalidité. Y a-t-il un plafond ?$QK$,
$QK$["Non, cumul intégral", "Oui — règle de SURINDEMNISATION : total des prestations (AI + LPP + LCA + revenu résiduel) ne peut EXCÉDER 90% du gain présumé perdu (art. 34a LPP + directives OFAS). Au-delà, réduction proportionnelle des prestations LPP en 1er.", "Plafond 50% du salaire", "Plafond 60% du salaire"]$QK$::jsonb,
1,
$QK$Coordination indemnités : la règle 90% vise à éviter que l'invalide gagne plus qu'en travaillant. Les prestations pouvant être réduites sont : LPP (en 1er), LCA, LAA. L'AI n'est pas réductible. Point à connaître pour évaluer la VRAIE couverture d'un client (parfois moins bonne que la somme des couvertures pense l'être).$QK$,
$QK$["Faux — plafond légal.", null, "Faux — 90% du gain présumé.", "Faux — 90%, pas 60%."]$QK$::jsonb,
$QK$Erreur = calculer une couverture cumulée qui dépasse 90% du salaire → client déçu qu'en réalité le plafond réduise ses rentes LCA. Devoir courtier = savoir dimensionner CORRECTEMENT en anticipant la surindemnisation.$QK$,
TRUE),

('prevoyance','P021','Retraite — Fiscalité capital vs rente','single',
$QK$Un client peut choisir entre 500k en capital LPP OU une rente à vie de 25k/an. Fiscalement, quelle option est la plus avantageuse ?$QK$,
$QK$["Toujours capital", "Toujours rente", "Analyse : CAPITAL imposé une fois à ~8-12% séparément (≈ 40-60k CHF impôt) puis capital à investir/gérer. RENTE imposée à 100% comme revenu ordinaire chaque année → taux marginal souvent 25-35% × 25k = 6-9k CHF/an. À espérance de vie 20 ans → 120-180k CHF impôt cumulé. Analyse individuelle nécessaire (âge, santé, patrimoine).", "Aucune différence"]$QK$::jsonb,
2,
$QK$La rente est imposée à 100% au taux marginal du revenu ordinaire. Sur 20 ans, l'impôt cumulé peut dépasser largement l'impôt sur un retrait en capital unique. MAIS le capital nécessite une gestion active (risque de mauvaise décision, dépenses excessives, arnaque). L'arbitrage doit intégrer : espérance de vie, taux marginal, discipline financière, situation matrimoniale (rente survivant).$QK$,
$QK$["Trop simple — dépend de l'espérance de vie et du marginal.", "Trop simple — la rente offre sécurité + rente survivant.", null, "Faux — écart fiscal peut atteindre 100 000+ CHF sur 20 ans."]$QK$::jsonb,
$QK$Erreur = conseil standardisé sans analyse chiffrée personnalisée. Devoir courtier = livrer un tableau comparatif capital/rente sur 20 ans intégrant fiscalité + risques. Différence pouvant atteindre 100-200k CHF.$QK$,
TRUE),

('prevoyance','P022','LPP — Taux de conversion','single',
$QK$Un salarié atteint la retraite avec un avoir LPP de 500k CHF. Sa caisse applique un taux de conversion de 6,8%. Quelle rente annuelle attend-il ?$QK$,
$QK$["Aucune rente", "34 000 CHF/an à vie (500 000 × 6,8%)", "50 000 CHF/an", "Le taux ne s'applique pas au retrait"]$QK$::jsonb,
1,
$QK$Taux de conversion : détermine la rente annuelle versée à partir de l'avoir accumulé. 500 000 × 6,8% = 34 000 CHF/an à vie. Taux LÉGAL MINIMUM sur la partie obligatoire = 6,8% (2026). Les caisses appliquent souvent 4,5-5,5% sur la partie SUROBLIGATOIRE (car surobligatoire non protégé par la loi). Distinction essentielle à connaître.$QK$,
$QK$["Faux — la rente existe.", null, "Faux — calcul 10% erroné.", "Faux — c'est le mécanisme principal du calcul rente."]$QK$::jsonb,
$QK$Erreur = ne pas simuler la rente attendue en amont de la retraite → client déçu quand il découvre 34k/an au lieu de 50k qu'il imaginait. Devoir = simulation transparente 5-10 ans avant retraite.$QK$,
TRUE),

('prevoyance','P023','Retraite anticipée','single',
$QK$Un salarié veut prendre sa retraite à 62 ans (au lieu de 65). Impact sur ses prestations ?$QK$,
$QK$["Aucun impact", "AVS : rente RÉDUITE de 6,8% par année d'anticipation → 20,4% de moins pour départ à 62 ans, à vie. LPP : réduction similaire selon règlement caisse. + on cotise 3 ans de moins = capital LPP plus faible. Nécessite souvent un 3a bien alimenté pour combler.", "AVS reste identique, LPP baisse un peu", "Rente identique mais versée plus tôt"]$QK$::jsonb,
1,
$QK$Retraite anticipée = double impact : (1) MOINS de cotisations donc capital plus faible, (2) REDUCTION de la rente pour compenser la durée de versement plus longue (6,8% par année d'anticipation). Ex : 65→62 = capital 15% + réduction 20,4% = perte de rente ≈ 30% par rapport à retraite à 65. Nécessite un plan financier solide pour combler.$QK$,
$QK$["Faux — impact structurel important.", null, "Sous-évalue — la réduction est aussi sur LPP + AVS + cumul.", "Faux — la rente EST réduite, pas juste avancée."]$QK$::jsonb,
$QK$Erreur = laisser un client faire sa retraite anticipée sans lui chiffrer précisément la baisse de revenu à vie. Il découvre à 62 ans qu'il perd 20-30% de rente pendant 25 ans = drame identifiable a posteriori.$QK$,
TRUE),

('prevoyance','P024','Réforme AVS21','single',
$QK$Réforme AVS21 (entrée en vigueur 2024-2028) : quel changement MAJEUR pour les femmes ?$QK$,
$QK$["Aucun changement femmes", "L'âge de la retraite ordinaire des femmes passe progressivement de 64 à 65 ans (harmonisation avec les hommes), sur une transition 2025-2028. Les femmes nées 1961+ sont concernées.", "Rente augmentée de 10%", "Retraite abaissée à 62 ans pour toutes"]$QK$::jsonb,
1,
$QK$AVS21 : harmonisation homme/femme à 65 ans, transition graduelle. Femme née 1961 → retraite 64+3 mois, 1962 → 64+6 mois, 1963 → 64+9 mois, 1964+ → 65 ans. Mesures compensatoires pour les femmes proches de la retraite (indemnisations, flexibilité). Base légale à connaître pour toute cliente >55 ans.$QK$,
$QK$["Faux — changement historique.", null, "Faux — pas d'augmentation.", "Faux — le contraire."]$QK$::jsonb,
$QK$Erreur = ne pas informer une cliente 60-65 ans de sa nouvelle date de retraite → elle prépare son budget sur l'ancienne norme, découvre le décalage à quelques mois de la retraite → surprise et incompréhension. Devoir informatif 2024-2028 spécifique.$QK$,
TRUE),

('prevoyance','P025','LPP — Rachats calcul','single',
$QK$Un salarié de 50 ans a un avoir LPP actuel de 400 000 CHF. Sa caisse indique un "avoir maximal théorique" de 620 000 CHF. Quel est son potentiel de rachat ?$QK$,
$QK$["620 000 CHF", "220 000 CHF (différence entre théorique et actuel)", "400 000 CHF", "Aucun — pas de rachat possible"]$QK$::jsonb,
1,
$QK$Le potentiel de rachat = différence entre l'avoir théorique (comme si il avait toujours cotisé au max) et l'avoir actuel. Ici 620k − 400k = 220 000 CHF de rachat possible. À utiliser progressivement (échelonner sur plusieurs années fiscales) pour maximiser la déduction fiscale marginale sans faire tomber le contribuable dans une tranche inférieure.$QK$,
$QK$["Faux — c'est le montant total théorique, pas le potentiel de rachat.", null, "Faux — c'est l'avoir actuel, pas le potentiel de rachat.", "Faux — potentiel existe."]$QK$::jsonb,
$QK$Erreur = ne pas identifier le potentiel de rachat pour un client aisé → milliers de CHF d'économie fiscale perdus par an. Le certificat de prévoyance annuel de la caisse LPP indique ce montant — le courtier doit le questionner.$QK$,
TRUE),

('prevoyance','P026','Assurance-vie — Types','single',
$QK$Différence entre assurance-vie CLASSIQUE (à taux garanti) et assurance-vie UNIT-LINKED (liée aux fonds) ?$QK$,
$QK$["Aucune", "CLASSIQUE : capital et rendement garantis par la compagnie (souvent 1-2% + participation aux bénéfices). Sécurité totale mais rendement modeste. UNIT-LINKED : capital investi en fonds d'investissement, rendement variable selon marchés, potentiel plus élevé mais risque de perte + frais généralement plus lourds.", "Classique est illégale", "Unit-linked est réservée aux entreprises"]$QK$::jsonb,
1,
$QK$Deux logiques opposées. CLASSIQUE = compagnie porte le risque (garantit un rendement minimum), primes plus chères. UNIT-LINKED = client porte le risque (fonds choisis dans un catalogue), primes plus basses, rendement potentiel plus élevé mais variable. Cas de figure typiques : classique pour prudents / retraite proche, unit-linked pour jeunes/tolérants au risque avec horizon long.$QK$,
$QK$["Faux — 2 mécanismes distincts.", null, "Faux — parfaitement légale.", "Faux — accessible aux particuliers."]$QK$::jsonb,
$QK$Erreur = vendre unit-linked à un client averse au risque qui panique à la 1re baisse et résilie → perte de rachat 30-50%. Devoir = tester la tolérance au risque AVANT proposition.$QK$,
TRUE),

('prevoyance','P027','Assurance-vie — Valeur rachat','single',
$QK$Un client résilie son assurance-vie mixte 3a après 8 ans. Il a versé 40 000 CHF de primes. Que va-t-il récupérer ?$QK$,
$QK$["40 000 CHF", "Environ 25-35 000 CHF selon compagnie et allocation. La valeur de rachat = réserve mathématique − frais de résiliation. Après 8 ans, la majeure partie des frais d'acquisition est amortie mais l'écart avec les primes payées reste significatif (pénalité résiduelle + rendement plus faible que la garantie théorique).", "50 000 CHF avec intérêts", "10 000 CHF"]$QK$::jsonb,
1,
$QK$Valeur de rachat après 8 ans ≈ 60-90% des primes versées selon contrat. Les frais d'acquisition (commissions, frais compagnie) sont amortis surtout dans les 5 premières années. Après 8-10 ans, la valeur de rachat commence à approcher les primes versées, mais reste inférieure à un placement bancaire équivalent. Le contrat prend son plein sens à ÉCHÉANCE (souvent 25-30 ans).$QK$,
$QK$["Faux — perte structurelle.", null, "Faux — la valeur de rachat ne dépasse jamais les primes en cas de résiliation anticipée.", "Trop pessimiste — après 8 ans les frais sont largement amortis."]$QK$::jsonb,
$QK$Erreur = ne pas prévenir de la perte de rachat même après 8 ans. Client résilie, découvre les 10-15k CHF de perte → plainte défaut de conseil. Le tableau de valeurs de rachat sur 30 ans doit être REMIS dès la souscription.$QK$,
TRUE),

('prevoyance','P028','LPP — Consolidation','single',
$QK$Un client a 3 avoirs de libre passage totalisant 380 000 CHF. Peut-il tout consolider dans SA caisse LPP actuelle ?$QK$,
$QK$["Non, interdit", "Oui — c'est une des rares utilisations autorisées pour les avoirs LP : les faire réintégrer dans la caisse LPP active en tant que rachat. Mais attention règle 79b al. 3 : blocage 3 ans avant retrait en capital.", "Oui sans limite", "Uniquement 50% consolidable"]$QK$::jsonb,
1,
$QK$Réintégration d'avoirs de libre passage dans la caisse LPP active = mécanisme autorisé (assimilé à un rachat volontaire). Avantages : capitalisation dans le régime LPP (souvent meilleur rendement), simplicité comptable à la retraite. Contre-partie : blocage art. 79b al. 3 LPP = pas de retrait capital dans les 3 ans suivant l'opération, sinon fiscalité annulée.$QK$,
$QK$["Faux — c'est autorisé et souvent conseillé.", null, "Faux — pas de limite mais règle de blocage 3 ans.", "Faux — pas de plafond 50%."]$QK$::jsonb,
$QK$Erreur = ne pas envisager la consolidation LPP + libre passage → client garde plusieurs comptes éparpillés à faible rendement → sous-optimisation. Ou à l'inverse, consolider juste avant la retraite → piège fiscal 3 ans. Timing critique.$QK$,
TRUE),

('prevoyance','P029','Prévoyance — Indépendants','single',
$QK$Un indépendant SANS 2e pilier (LPP) veut se constituer une prévoyance. Options ?$QK$,
$QK$["3a limité comme salarié à 7 056 CHF/an", "Peut cotiser au 3a jusqu'à 20% du revenu net avec plafond 35 280 CHF/an (2026) — dit 3a 'gros plafond' indépendant. Peut aussi s'affilier volontairement à la Fondation Institution Supplétive (LPP) ou à une caisse professionnelle.", "Aucune option", "Uniquement l'AVS"]$QK$::jsonb,
1,
$QK$Indépendant SANS LPP = plafond 3a majoré à 20% du revenu net (max 35 280 CHF/an en 2026). C'est un gros levier d'optimisation fiscale : sur un revenu de 150k, il peut déduire jusqu'à 30k CHF/an. En parallèle, il peut affilier volontairement une LPP (Fondation Institution Supplétive ou caisse professionnelle) → double couverture retraite + économies fiscales renforcées.$QK$,
$QK$["Sous-évalue — plafond majoré pour indépendants.", null, "Faux — plusieurs options existent.", "Faux — options multiples au-delà de l'AVS."]$QK$::jsonb,
$QK$Erreur = laisser un indépendant à haut revenu au plafond 3a salarié (7 056) alors qu'il pourrait déduire 35 280 CHF/an → perte fiscale ≈ 10-13k CHF/an, cumulée 15-20 ans = 200k+ CHF perdus. Devoir courtier majeur.$QK$,
TRUE),

('prevoyance','P030','Prévoyance — Départ Suisse','single',
$QK$Un client Klary part vivre définitivement au Portugal (UE). Que devient son 3a et sa LPP ?$QK$,
$QK$["Retrait cash intégral", "3a : retrait cash possible avec justificatif départ définitif. LPP : IMPOSSIBLE de retirer en cash dans un pays UE/AELE — l'avoir reste en Suisse (compte libre passage) et sera versé à l'âge de la retraite. HORS UE/AELE : retrait cash possible pour LPP + 3a.", "Rien ne bouge", "Tout est perdu"]$QK$::jsonb,
1,
$QK$Depuis 2007, la LPP obligatoire NE PEUT PLUS être retirée en cash pour un départ dans un pays UE/AELE (accord bilatéral coordination). Elle reste sur un compte libre passage suisse. À l'âge de la retraite, l'avoir est versé (en rente ou capital selon règles caisse). Le 3a et la PARTIE SUROBLIGATOIRE de la LPP restent retirables en cash pour départ UE. HORS UE/AELE (ex: USA, Maroc, Brésil, Australie) : retrait cash LPP + 3a possible avec justificatifs.$QK$,
$QK$["Faux — LPP obligatoire non retirable en UE.", null, "Sous-évalue — le 3a et surobligatoire LPP peuvent être libérés.", "Faux — l'avoir reste acquis."]$QK$::jsonb,
$QK$Erreur = client qui projette un déménagement UE en comptant récupérer 400k LPP cash → drame budgétaire quand il découvre la blockage. Point crucial à connaître pour tout client expatrié.$QK$,
TRUE),

('prevoyance','P031','Prévoyance — Prestations en cascade','single',
$QK$Un salarié de 40 ans meurt subitement d'une crise cardiaque (donc MALADIE, pas accident). Quelles prestations obligatoires pour sa famille ?$QK$,
$QK$["Rien, mort par maladie", "AVS : rente veuf/veuve (si conditions remplies) + rentes orphelins jusqu'à 18/25 ans. LPP : rente conjoint 60% de la rente d'invalidité potentielle + rente orphelin 20%/enfant. LAA n'intervient PAS (accident seulement).", "Uniquement AVS", "Capital 3a uniquement"]$QK$::jsonb,
1,
$QK$Décès par maladie : cascade AVS + LPP (mais PAS LAA — celle-ci ne couvre que les accidents). Souvent la LAMal ne prévoit rien pour les survivants. LACUNE potentielle si le salaire du défunt était haut : les rentes AVS+LPP survivants représentent souvent 40-55% du dernier salaire. À compléter par LCA vie décès (temporaire ou mixte) selon situation familiale.$QK$,
$QK$["Faux — prestations existent.", null, "Sous-estime — LPP existe aussi.", "Faux — 3a est une composante mais pas la seule."]$QK$::jsonb,
$QK$Erreur = ne pas dimensionner la LCA décès en fonction du gap réel après AVS+LPP. Famille se retrouve avec 40-50% du revenu → drame. LCA décès temporaire est peu coûteuse et essentielle pour familles avec enfants.$QK$,
TRUE),

('prevoyance','P032','Prévoyance — 3a maximum comptes','single',
$QK$Un client a-t-il un nombre maximum de comptes 3a qu'il peut ouvrir ?$QK$,
$QK$["Un seul autorisé", "Aucun plafond légal officiel, mais stratégiquement 3-5 comptes maximum recommandés. Chaque compte peut être RETIRÉ INDIVIDUELLEMENT à la retraite sur une année fiscale distincte → optimise le barème progressif de la prestation en capital. Beyond 5 comptes = complexité de gestion sans gain fiscal supplémentaire notable.", "Maximum 2 comptes", "10 comptes"]$QK$::jsonb,
1,
$QK$Stratégie 3a courante : ouvrir progressivement 3-5 comptes (chez différents établissements, ou 3a titres + 3a bancaire) au fil des ans. À la retraite, retirer 1 compte par année fiscale sur 3-5 ans → chaque retrait passe dans une tranche fiscale basse. Économie fiscale cumulée : 5-15% selon canton et montant total, soit 10-40k CHF sur 500k total.$QK$,
$QK$["Faux — aucun plafond légal.", null, "Sous-estime — 3-5 comptes recommandés.", "Excessif — complexité sans gain."]$QK$::jsonb,
$QK$Erreur = un client qui garde tout sur 1 compte 3a = concentration fiscale à la retraite, perte 10-40k CHF potentielle. Le courtier compétent explique la stratégie multi-comptes AU DÉMARRAGE, pas 30 ans plus tard.$QK$,
TRUE),

('prevoyance','P033','Prévoyance — Enfants sans revenu','single',
$QK$Peut-on ouvrir un 3a au nom d'un enfant mineur sans revenu ?$QK$,
$QK$["Oui, comme un adulte", "NON — le 3a nécessite un revenu SOUMIS À L'AVS (art. 82 LPP). Les enfants sans revenu ne peuvent pas cotiser. À partir de 18 ans avec un apprentissage/travail rémunéré → oui. Alternative pour enfants : ouvrir un 3b (assurance-vie enfants) ou compte-titres au nom de l'enfant, sans avantage fiscal 3a.", "Uniquement dès 15 ans", "Oui mais capital limité"]$QK$::jsonb,
1,
$QK$Art. 82 LPP : seuls les personnes exerçant une activité lucrative soumise à l'AVS peuvent cotiser au 3a. Pas de 3a pour enfants sans revenu, pas de 3a pour retraités, pas de 3a pour personnes au chômage sans activité intermédiaire. Alternative épargne enfants : 3b libre, compte-titres, assurance-vie enfants (pas d'avantage fiscal fédéral).$QK$,
$QK$["Faux — critère revenu obligatoire.", null, "Sous-évalue — 18 ans mais avec revenu obligatoire.", "Faux — critère de fond, pas de plafond."]$QK$::jsonb,
$QK$Erreur = démarcher des parents pour "ouvrir un 3a à votre enfant" → refus institution → perte de crédibilité. Connaissance de base des critères d'accès.$QK$,
TRUE),

('prevoyance','P034','Prévoyance — Concubinage donation','single',
$QK$Une cliente concubine (10 ans de vie commune, 1 enfant) souhaite désigner son concubin comme bénéficiaire 3a en cas de décès. C'est possible ?$QK$,
$QK$["Non, jamais", "Oui SI les conditions sont remplies : cohabitation ≥ 5 ans OU enfant commun à charge, désignation ÉCRITE auprès de l'institution 3a, pas d'autre conjoint marié parallèle. Sans désignation, l'ordre légal art. 2 OPP3 s'applique et l'enfant hérite avant le concubin.", "Uniquement 50%", "Interdit par la LPP"]$QK$::jsonb,
1,
$QK$Depuis 2005, désignation du concubin comme bénéficiaire 3a possible sous 3 conditions cumulatives. ATTENTION : la désignation n'est PAS AUTOMATIQUE — il faut la faire écrite à l'institution. Beaucoup de concubins l'ignorent et le survivant se retrouve sans rien (l'enfant hérite en priorité selon ordre légal). Point à aborder systématiquement avec couples non-mariés.$QK$,
$QK$["Faux — c'est autorisé sous conditions.", null, "Faux — désignation intégrale possible.", "Faux — c'est expressément permis."]$QK$::jsonb,
$QK$Erreur = ne pas systématiser la question "êtes-vous marié ou concubin ?" et proposer la désignation → survivant sans droit à sa mort → drame. Le concubin survivant peut se retrouver dans la rue si l'enfant commun est mineur et hérite du 3a.$QK$,
TRUE),

('prevoyance','P035','Prévoyance — Cotisations non versées','single',
$QK$Une salariée est en congé maternité 4 mois. Sa caisse LPP cotise-t-elle pendant cette période ?$QK$,
$QK$["Non, cotisations suspendues", "Oui — l'employeur maintient les cotisations LPP employeur + employée pendant tout le congé maternité (14 semaines minimum + éventuel congé prolongé). L'avoir de vieillesse continue de croître normalement.", "Uniquement employeur", "Uniquement à 50%"]$QK$::jsonb,
1,
$QK$Loi maternité + LAmat + jurisprudence : les cotisations LPP sont MAINTENUES intégralement pendant le congé maternité (indemnisation maternité 80% du salaire, calculée sur le dernier salaire précédant l'accouchement). Cotisations = salaire assuré normal, pas de suspension. Idem pour un congé maladie prolongé sous LCA perte de gain.$QK$,
$QK$["Faux — cotisations maintenues.", null, "Faux — les 2 cotisations (employeur + employé) continuent.", "Faux — plein tarif."]$QK$::jsonb,
$QK$Erreur = paniquer une future maman en lui disant qu'elle va perdre 4 mois de cotisations LPP → fausse info. Devoir informatif rassurant.$QK$,
TRUE)

ON CONFLICT DO NOTHING;
